# Generated by Django 4.2.3 on 2023-07-19 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_cake_description_cake_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
