# Generated by Django 4.2.3 on 2023-07-22 03:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0007_remove_customuser_groups_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="email",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="password",
        ),
    ]
