# Generated by Django 4.2.3 on 2023-07-19 00:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="Имя заказчика")),
                (
                    "phonenumber",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="Номер телефона"
                    ),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=100, verbose_name="адрес"),
                ),
                (
                    "comment",
                    models.TextField(blank=True, verbose_name="Комментарий к заказу"),
                ),
                (
                    "delivery_date",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Дата доставки",
                    ),
                ),
                (
                    "delivery_time",
                    models.TimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Время доставки",
                    ),
                ),
                ("price", models.IntegerField(verbose_name="Стоимость торта")),
                (
                    "levels",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="Уровни торта"
                    ),
                ),
                (
                    "form",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="Форма торта"
                    ),
                ),
                (
                    "topping",
                    models.CharField(blank=True, max_length=50, verbose_name="Топпинг"),
                ),
                (
                    "berries",
                    models.CharField(blank=True, max_length=50, verbose_name="Ягоды"),
                ),
                (
                    "decor",
                    models.CharField(blank=True, max_length=90, verbose_name="Декор"),
                ),
                (
                    "inscription",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Надпись на торте"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен ли заказ"),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
            },
        ),
    ]
