# Generated by Django 4.2.3 on 2023-07-19 00:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="deliv_comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="Комментарий к заказу"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
