# Generated by Django 4.2.3 on 2023-07-19 00:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0003_remove_order_deliv_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="deliv_comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="Комментарий к заказу"
            ),
        ),
    ]
