# Generated by Django 4.2.3 on 2023-07-19 00:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0004_order_deliv_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="price",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Стоимость торта"
            ),
        ),
    ]
