# Generated by Django 4.2.3 on 2023-07-19 01:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0005_alter_order_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="deliv_comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="Комментарий для курьера"
            ),
        ),
    ]
