# Generated by Django 4.2.3 on 2023-07-20 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0005_cake_name"),
        ("order", "0006_alter_order_deliv_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="ready_cake",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_cakes",
                to="shop.cake",
            ),
        ),
    ]
